// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZUDHmSKBSkcZOhGHkgqIC4Y0bOw5oeQ',
    appId: '1:831456807199:web:1474431de585705bcb882a',
    messagingSenderId: '831456807199',
    projectId: 'rave-trade-ca544',
    authDomain: 'rave-trade-ca544.firebaseapp.com',
    storageBucket: 'rave-trade-ca544.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWdHcAzfetx405yG6TvZp4MJ6DrVbS_Y',
    appId: '1:831456807199:android:3396f8cd2f532f41cb882a',
    messagingSenderId: '831456807199',
    projectId: 'rave-trade-ca544',
    storageBucket: 'rave-trade-ca544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8pwIjcM_BQEdaPMT_hQDZNtWeLgR2WI',
    appId: '1:831456807199:ios:dcb563f0c5dc975ccb882a',
    messagingSenderId: '831456807199',
    projectId: 'rave-trade-ca544',
    storageBucket: 'rave-trade-ca544.appspot.com',
    iosBundleId: 'com.example.ticketResale',
  );
}
